version: '3.8'

services:
  film-scheduler:
    build: .
    container_name: film-scheduler-v6
    restart: unless-stopped
    ports:
      - "5076:5000"  # Changed from 5075 to avoid conflict with v5
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
    environment:
      - TZ=Europe/Dublin
      - VIEWER_PASSWORD=${VIEWER_PASSWORD}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD}
      - SECRET_KEY=${SECRET_KEY}
      - FLASK_ENV=${FLASK_ENV:-development}
      - FLASK_DEBUG=${FLASK_DEBUG:-1}
      - PYTHONUNBUFFERED=1
    networks:
      - film-scheduler-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  film-scheduler-network:
    driver: bridge

volumes:
  scheduler-data:
    driver: local
